// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/user/:userId": {
    params: {
      "userId": string;
    };
  };
  "/admin/edit/:userId": {
    params: {
      "userId": string;
    };
  };
  "/admin/transactions/:userId": {
    params: {
      "userId": string;
    };
  };
  "/admin/cards/:userId": {
    params: {
      "userId": string;
    };
  };
  "/admin/notifications/:userId": {
    params: {
      "userId": string;
    };
  };
  "/admin/transfer/:userId": {
    params: {
      "userId": string;
    };
  };
  "/admin/create": {
    params: {};
  };
  "/admin/settings": {
    params: {};
  };
  "/admin/otp": {
    params: {};
  };
  "/admin/send-mails": {
    params: {};
  };
  "/admin/create-trans/:userId": {
    params: {
      "userId": string;
    };
  };
  "/admin/edit-notification/:id/:userId": {
    params: {
      "id": string;
      "userId": string;
    };
  };
  "/admin/create-notification/:userId": {
    params: {
      "userId": string;
    };
  };
  "/admin/deposit/:userId": {
    params: {
      "userId": string;
    };
  };
  "/admin/edit-trans/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/card/create-trans/:id/:userId": {
    params: {
      "id": string;
      "userId": string;
    };
  };
  "/admin/card/edit-card/:userId/:cardId/:transactionId": {
    params: {
      "userId": string;
      "cardId": string;
      "transactionId": string;
    };
  };
  "/chats": {
    params: {};
  };
  "/api/get-recipient": {
    params: {};
  };
  "/api/send-mail": {
    params: {};
  };
  "/api/x1/create": {
    params: {};
  };
  "/api/get-data": {
    params: {};
  };
  "/api/logout": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/admin" | "/admin/user/:userId" | "/admin/edit/:userId" | "/admin/transactions/:userId" | "/admin/cards/:userId" | "/admin/notifications/:userId" | "/admin/transfer/:userId" | "/admin/create" | "/admin/settings" | "/admin/otp" | "/admin/send-mails" | "/admin/create-trans/:userId" | "/admin/edit-notification/:id/:userId" | "/admin/create-notification/:userId" | "/admin/deposit/:userId" | "/admin/edit-trans/:id" | "/admin/card/create-trans/:id/:userId" | "/admin/card/edit-card/:userId/:cardId/:transactionId" | "/chats" | "/api/get-recipient" | "/api/send-mail" | "/api/x1/create" | "/api/get-data" | "/api/logout" | "/*";
  };
  "./routes/login.tsx": {
    id: "routes/login";
    page: "/";
  };
  "./dashboard.tsx": {
    id: "dashboard";
    page: "/admin" | "/admin/user/:userId" | "/admin/edit/:userId" | "/admin/transactions/:userId" | "/admin/cards/:userId" | "/admin/notifications/:userId" | "/admin/transfer/:userId" | "/admin/create" | "/admin/settings" | "/admin/otp" | "/admin/send-mails" | "/admin/create-trans/:userId" | "/admin/edit-notification/:id/:userId" | "/admin/create-notification/:userId" | "/admin/deposit/:userId" | "/admin/edit-trans/:id" | "/admin/card/create-trans/:id/:userId" | "/admin/card/edit-card/:userId/:cardId/:transactionId";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/admin";
  };
  "./routes/user.tsx": {
    id: "routes/user";
    page: "/admin/user/:userId";
  };
  "./routes/edit.tsx": {
    id: "routes/edit";
    page: "/admin/edit/:userId";
  };
  "./routes/transactions.tsx": {
    id: "routes/transactions";
    page: "/admin/transactions/:userId";
  };
  "./routes/cards.tsx": {
    id: "routes/cards";
    page: "/admin/cards/:userId";
  };
  "./routes/notifications.tsx": {
    id: "routes/notifications";
    page: "/admin/notifications/:userId";
  };
  "./routes/transfer.tsx": {
    id: "routes/transfer";
    page: "/admin/transfer/:userId";
  };
  "./routes/create.tsx": {
    id: "routes/create";
    page: "/admin/create";
  };
  "./routes/settings.tsx": {
    id: "routes/settings";
    page: "/admin/settings";
  };
  "./routes/otp.tsx": {
    id: "routes/otp";
    page: "/admin/otp";
  };
  "./routes/send-mails.tsx": {
    id: "routes/send-mails";
    page: "/admin/send-mails";
  };
  "./routes/create-trans.tsx": {
    id: "routes/create-trans";
    page: "/admin/create-trans/:userId";
  };
  "./routes/edit-notification.tsx": {
    id: "routes/edit-notification";
    page: "/admin/edit-notification/:id/:userId";
  };
  "./routes/create-notification.tsx": {
    id: "routes/create-notification";
    page: "/admin/create-notification/:userId";
  };
  "./routes/deposit.tsx": {
    id: "routes/deposit";
    page: "/admin/deposit/:userId";
  };
  "./routes/edit-trans.tsx": {
    id: "routes/edit-trans";
    page: "/admin/edit-trans/:id";
  };
  "./routes/card-trans.tsx": {
    id: "routes/card-trans";
    page: "/admin/card/create-trans/:id/:userId";
  };
  "./routes/edit-card.tsx": {
    id: "routes/edit-card";
    page: "/admin/card/edit-card/:userId/:cardId/:transactionId";
  };
  "./routes/chats.tsx": {
    id: "routes/chats";
    page: "/chats";
  };
  "./api/get-recipient.tsx": {
    id: "api/get-recipient";
    page: "/api/get-recipient";
  };
  "./api/mail.tsx": {
    id: "api/mail";
    page: "/api/send-mail";
  };
  "./api/create-admin.tsx": {
    id: "api/create-admin";
    page: "/api/x1/create";
  };
  "./api/get-admin.tsx": {
    id: "api/get-admin";
    page: "/api/get-data";
  };
  "./api/logout.tsx": {
    id: "api/logout";
    page: "/api/logout";
  };
  "./routes/404.tsx": {
    id: "routes/404";
    page: "/*";
  };
};